import type { Metadata } from "next";
import { Livvic, Reddit_Mono } from "next/font/google";
import "./globals.css";

const redditMono = Reddit_Mono({
  weight: "300",
});

const livvicMed = Livvic({
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${livvicMed} ${redditMono} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
